Repository codidact/qpixel, pull requests merged in 2020-10, with the labels that each got.

#183 Fix issue with externally hosted images
  app/controllers/advertisement_controller.rb
Labels: hacktoberfest

#184 Fix keyboard tools and mentions
  app/assets/javascripts/keyboard_tools.js
  app/assets/stylesheets/keyboard_tools.scss
  app/controllers/application_controller.rb
  app/controllers/comments_controller.rb
  app/views/application/keyboard_tools.html.erb
  app/views/users/edit_profile.erb
  config/routes.rb
Labels: hacktoberfest, hacktoberfest-accepted

#209 Add a Birthday Challenge Ranking page
  app/assets/javascripts/birthday.coffee
  app/assets/stylesheets/birthday.scss
  app/controllers/birthday_controller.rb
  app/helpers/birthday_helper.rb
  app/views/birthday/index.html.erb
  app/views/birthday/ranking.html.erb
  config/routes.rb
  public/assets/birthday.svg
  public/assets/undraw_happy_birthday_s72n.svg:Zone.Identifier
  test/controllers/birthday_controller_test.rb
Labels: hacktoberfest, hacktoberfest-accepted

#223 Fix first visit notice
  app/assets/javascripts/application.js
  app/views/layouts/application.html.erb
  app/views/layouts/without_sidebar.html.erb
Labels: hacktoberfest-accepted
