Repository codidact/qpixel, pull requests merged in 2023-08, with the labels that each got.

#1110 Speed up tests significantly
  test/test_helper.rb
Labels: priority: high

#1146 Stop using broken query url in many places
  app/views/admin/audit_log.html.erb
  app/views/categories/show.html.erb
  app/views/posts/show.html.erb
  app/views/search/search.html.erb
  app/views/users/index.html.erb
  app/views/users/posts.html.erb
Labels: type: bug, priority: high, complexity: easy

#1131 239 after login redirect to the original page
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/users/saml_sessions_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users_controller.rb
Labels: priority: high

#1148 Fix incorrect sign in behavior
  app/controllers/users/sessions_controller.rb
Labels: priority: high

#1182 Fix name of the sample .irbrc file in Docker's local-setup script
  docker/local-setup.sh
Labels: type: bug

#1183 Fix not being able to edit privilege thresholds to 0 from the admin panel
  app/assets/javascripts/privileges.js
Labels: type: bug

#1188 Fix invalid profile website URI causing a 500 error page on invalid URIs
  app/controllers/users_controller.rb
Labels: area: ruby, type: bug
