Repository codidact/qpixel, pull requests merged in 2023-12, with the labels that each got.

#1267 Fix character counter in tag excerpt fields
  app/views/posts/_form.html.erb
  app/views/posts/_mdhint.html.erb
  app/views/shared/_body_field.html.erb
  app/views/tags/_form.html.erb
  app/views/users/edit_profile.html.erb
Labels: area: ruby

#1238 Fix "Custom" filter name not showing up when the filter has an empty name
  app/views/categories/show.html.erb
Labels: area: ruby, type: bug

#1233 Update to rails 7.0.8
  Gemfile.lock
Labels: dependencies

#1268 Display existing flags in flag dialog
  app/controllers/posts_controller.rb
  app/controllers/tags_controller.rb
  app/models/user.rb
  app/views/posts/_expanded.html.erb
Labels: area: ruby, area: html/css/js, type: change request
