Repository codidact/qpixel, pull requests merged in 2025-01, with the labels that each got.

#1491 Fix server error on user profile vote summary tab if there are orphaned votes
  app/controllers/users_controller.rb
  app/jobs/cleanup_votes_job.rb
  app/models/vote.rb
  app/views/users/vote_summary.html.erb
  config/locales/strings/en.votes.yml
  config/schedule.rb
  scripts/cleanup_votes.rb
Labels: area: ruby, complexity: easy

#1504 Make docker-compose.yml configurable
  .gitignore
  docker/README.md
  docker/compose-env
  docker/local-setup.sh
Labels: type: configuration, area: deployment

#1508 Followup fix for search
  app/helpers/search_helper.rb
Labels: area: backend, priority: high

#1518 Followup fix for namespaced Redis cache handling of include_community
  lib/namespaced_env_cache.rb
Labels: area: backend, priority: high

#1519 Notify user on ability grant
  app/controllers/users_controller.rb
  app/models/community_user.rb
  db/migrate/20200813132829_enforce_concurrence_of_is_moderator_and_mod_ability.rb
  scripts/recalc_abilities.rb
  scripts/recalc_abilities_upon_first_migration.rb
  test/models/user_test.rb
Labels: area: backend, type: change request, priority: medium

#1525 Followup fix for cache & global site setttings handling
  app/assets/stylesheets/site_settings.scss
  app/controllers/site_settings_controller.rb
  app/models/site_setting.rb
  app/views/site_settings/index.html.erb
Labels: area: backend
