Repository codidact/qpixel, pull requests merged in 2025-07, with the labels that each got.

#1691 Changes to emails
  app/controllers/admin_controller.rb
  app/controllers/users/registrations_controller.rb
  app/mailers/admin_mailer.rb
  app/mailers/user_mailer.rb
  app/models/site_setting.rb
  app/views/layouts/_head.html.erb
  app/views/user_mailer/deletion_confirmation.html.erb
  app/views/users/qr_login_code.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/locales/strings/en.g.yml
  db/seeds/site_settings.yml
  test/controllers/admin_controller_test.rb
  test/mailers/admin_mailer_test.rb
  test/mailers/donation_mailer_test.rb
  test/mailers/previews/user_mailer_preview.rb
  test/mailers/user_mailer_test.rb
  test/test_helper.rb
Labels: area: backend, area: frontend, priority: high

#1513 Testing improvements
  .circleci/config.yml
  .github/workflows/ci-cd.yml
  .github/workflows/typescript.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/categories_controller.rb
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  app/models/category.rb
  app/models/post.rb
  app/models/user.rb
  test/controllers/categories_controller_test.rb
  test/controllers/posts/create_test.rb
  test/fixtures/categories.yml
  test/fixtures/community_users.yml
  test/fixtures/posts.yml
  test/helpers/search_helper_test.rb
  test/models/post_test.rb
Labels: area: testing

#1702 Comment thread inputs no longer enable the submit button when the default comment's body is not filled in
  app/assets/javascripts/character_count.js
  app/controllers/comments_controller.rb
  app/views/comments/_new_thread_modal.html.erb
Labels: status: blocked

#1704 Fix for the "0 available post types" case when clicking on the "Create Post" button
  app/controllers/categories_controller.rb
  app/models/category.rb
  app/views/categories/category_post_types.html.erb
  app/views/categories/post_types.html.erb
  app/views/layouts/_header.html.erb
Labels: status: blocked
