Repository codidact/qpixel, pull requests merged in 2025-05, with the labels that each got.

#1610 Fix missing usernames on Code Golf leaderboard
  public/assets/community/codegolf.js
Labels: area: frontend, area: assets

#1601 Update JS to use QPixel fetch API
  app/assets/javascripts/caret.js
  app/assets/javascripts/categories.js
  app/assets/javascripts/closure.js
  app/assets/javascripts/comments.js
  app/assets/javascripts/flags.js
  app/assets/javascripts/markdown.js
  app/assets/javascripts/notifications.js
  app/assets/javascripts/posts.js
  app/assets/javascripts/privileges.js
  app/assets/javascripts/qpixel_api.js
  app/assets/javascripts/reactions.js
  app/assets/javascripts/search.js
  app/assets/javascripts/site_settings.js
  app/assets/javascripts/subscriptions.js
  app/assets/javascripts/suggested_edit.js
  app/assets/javascripts/tag_sets.js
  app/assets/javascripts/tags.js
  app/assets/javascripts/textarea_popup.js
  app/assets/javascripts/two_factor.js
  app/assets/javascripts/users.js
  app/assets/javascripts/votes.js
  global.d.ts
Labels: area: frontend

#1614 Fix for JS handling of image submissions when creating / editing posts
  app/assets/javascripts/posts.js
Labels: area: frontend, priority: high

#1615 General minor fixes
  .gitignore
  app/assets/javascripts/posts.js
Labels: area: frontend

#1622 Fix role_toggle breaking due to access control methods rename
  app/controllers/users_controller.rb
  app/views/users/mod_privileges.html.erb
  test/controllers/users_controller_test.rb
  test/fixtures/user_abilities.yml
Labels: priority: high

#1619 Move bulleted/ordered list and tables editor buttons to the first level
  app/helpers/markdown_tools_helper.rb
  app/views/shared/_markdown_tools.html.erb
Labels: area: frontend
