Repository codidact/qpixel, pull requests merged in 2025-03, with the labels that each got.

#1556 Remove server.pid in the entrypoint if present
  docker/entrypoint.sh
Labels: area: deployment

#1573 cleaning up after dependabot's breaking of nokogiri
  Gemfile.lock
Labels: dependencies, area: deployment

#1558 Add `overflow-wrap`s to several elements currently overflowing
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/posts.scss
  app/assets/stylesheets/utilities.scss
  app/views/posts/_list.html.erb
  app/views/tags/show.html.erb
Labels: area: frontend

#1587 fixed max-width override taking over droppanel's max-width in posts
  app/assets/stylesheets/posts.scss
Labels: area: frontend
